service: product-service
frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    TABLE_NAME_ONE: products
    TABLE_NAME_TWO: stocks
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "arn:aws:dynamodb:us-east-1:164051493317:table/products"
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "arn:aws:dynamodb:us-east-1:164051493317:table/stocks"   
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }


custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false
    packager: "npm"
    excludeFiles: tests/*.test.js

functions:
  getProductsList:
    handler: src/handler.getProductsList
  getProductsById:
    handler: src/handler.getProductsById
  createProduct:
    handler: src/handler.createProduct
  hello:
    handler: src/handler.hello
