service: import-service
frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  httpApi:
    cors: true
  environment:
    FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileBucketName}
    SQS_URL: ${self:custom.sqsUrl}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource: "arn:aws:s3:::${self:custom.fileBucketName}"

        - Effect: "Allow"
          Action: "s3:*"
          Resource: "arn:aws:s3:::${self:custom.fileBucketName}/*"

        - Effect: "Allow"
          Action: "sqs:*"
          Resource: ${self:custom.sqsArn}

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false
    packager: "npm"
    excludeFiles: tests/*.test.js
  fileBucketName: ashish-uploaded
  sqsArn: arn:aws:sqs:us-east-1:164051493317:catalogItemsQueue
  sqsUrl: https://sqs.us-east-1.amazonaws.com/164051493317/catalogItemsQueue

functions:
  importProductsFile:
    architecture: arm64
    handler: src/handler.importProductsFile
    events:
      - httpApi:
          path: /import/{fileName}
          method: GET
  importFileParser:
    architecture: arm64
    handler: src/handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.fileBucketName}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: "uploaded/"
